export const blogData = [
  {
    title: "Tips for a Perfect Wedding Day",
    timestamp: "March 15, 2023",
    content:
      "<p>Here are some tips for making your wedding day truly special...</p>",
    likes: 15,
    comments: 5,
    imageUrl: "/images/wedding.jpg", // replace with your image URL
  },
];

export const plannerData = [
  {
    name: " Yuvik Weddings and Events ",
    contact: "90079 96697",
    address: ", Sector 3, Bidhannagar, Kolkata 700106",
    url: "https://yuvikevents.com/book-appointment/",
    rating: "5",
  },
  {
    name: " Dalliance Events",
    contact: "93308 74947",
    address: "Sinthee, Kolkata, 700050",
    url: "",
    rating: "5",
  },
  {
    name: "Afterlife Events & Entertainment ",
    contact: "91632 26709",
    address: "Kolkata , Howrah",
    url: "",
    rating: "5",
  },
  {
    name: "Karyakram Events",
    contact: "89104 96431",
    address: "Kolkata",
    url: "https://karyakramevents.com",
    rating: "5",
  },
  {
    name: "Momento Events Pvt. Ltd.",
    contact: "89610 44790",
    address: "Park Street , Kolkata",
    url: "",
    rating: "5",
  },
  {
    name: " Colour Your Canvas Events",
    contact: "91470 54648",
    address: "New Alipore, Kolkata, 700053",
    url: "https://cycevents.in/",
    rating: "5",
  },
  {
    name: "Onestop Weddings",
    contact: "9830111901",
    address: "Prafulla Sarkar Street Kolkata - 700001",
    url: "https://www.onestopweddings.in/",
    rating: "5",
  },
  {
    name: "DSR Event Planner",
    contact: "6289380112",
    address: "Tollygaunge",
    url: "http://www.dsreventplanner.com/",
    rating: "5",
  },
  {
    name: "Saymber Wedding Planner",
    contact: "70440 74047",
    address: "Kalikapur Rd, Kolkata, 700078",
    url: "",
    rating: "5",
  },
  {
    name: "Da louie Event Planner",
    contact: "70440 00821",
    address: "Basudevpur Colony, Kolkata, 700008",
    url: "",
    rating: "5",
  },
  {
    name: "Orion Events",
    contact: "99030 89646",
    address: "Sovabazar, Hatkhola, Kolkata, West Bengal 700005",
    url: "http://www.orioncaterersandevents.in/",
    rating: "5",
  },
  {
    name: "The Royal Reception",
    contact: "98364 60606",
    address: "Rabindra Sarani Kolkata Gpo, Kolkata 700003",
    url: "https://theroyalreception.com/",
    rating: "5",
  },
  {
    name: "Wedding Sutra Event Management",
    contact: "90511 99999",
    address: "Beadon Street, Kolkata",
    url: "https://weddingsutra.co.in/",
    rating: "5",
  },
  {
    name: "Silver Sand Event Management",
    contact: "98311 77461",
    address: "Garfa Main Road, Haltu, Kolkata - 700078",
    url: "https://www.silversandevent.com/",
    rating: "5",
  },
  {
    name: "Marriageuana",
    contact: "98300 49050",
    address: "25/7, Rustamjee St, Ballygunge Place, , Kolkata,-700019",
    url: "https://www.marriageuana.com/",
    rating: "5",
  },
  {
    name: "7th Heaven Event Planner",
    contact: "90515 45450",
    address: "  276, AA Block, Sector 1, Bidhannagar, Kolkata, 700064",
    url: "http://www.7thheavenweddings.com/",
    rating: "5",
  },
  {
    name: "Moksh Events Pvt Ltd",
    contact: "98316 69698",
    address: "19/6 Sahapur Colony , New Alipore Kolkata  700053",
    url: "https://www.mokshevents.com/",
    rating: "5",
  },
  {
    name: "Aashirwaad Events",
    contact: "87770 45982",
    address: "158/17, Belilious Road, Howrah, Kolkata 711101",
    url: "http://www.aashirwaadevent.com/",
    rating: "5",
  },
  {
    name: "High Heels Events",
    contact: "98753  40508",
    address: "17, Mother Teresa Sarani Taltala Kolkata 700016",
    url: "",
    rating: "5",
  },
  { name: "", contact: "", address: "", url: "", rating: "5" },
  {
    name: "Fortunate Events",
    contact: "97488 04738",
    address: "388/13, Upen Banerjee Rd, Taratala, Kolkata 700060",
    url: "",
    rating: "5",
  },
  {
    name: "Subha Muhurat",
    contact: "90075 39686",
    address: "ground floor, 2, 109B, Baghajatin Rd, Sree Colony Kolkata 700092",
    url: "",
    rating: "5",
  },
  {
    name: "Swastik wedding planner",
    contact: "82402 67595",
    address: "89 green park, Block A, Kolkata 700055",
    url: "https://swastikeventsco.com/",
    rating: "5",
  },
  {
    name: "Double Apple Entertainment",
    contact: "89815 39226",
    address: "46, Bangur Ave, Bangur, Lake Town, Kolkata 700055",
    url: "",
    rating: "5",
  },
  {
    name: "Kolkata Surprise Planner",
    contact: "70031 80748",
    address: "51, 32A, Dum Dum Rd, ,Kolkata, 700074",
    url: "",
    rating: "5",
  },
];

export const photographersData = [
  {
    name: "The Sparkling Wedding",
    contact: "7439968048",
    address:
      "8, 2/1A, Dhiren Sen Sarani, Manicktala, Azad Hind Bag, Kolkata 700006",
    url: "https://www.thesparklingwedding.com/",
    rating: "5",
  },
  {
    name: "Wedding Photo Creators",
    contact: "8617289391",
    address: "23/15 D.P.P Lane, Kolkata,700047",
    url: "https://www.weddingphotocreators.com/",
    rating: "5",
  },
  {
    name: "PixipFoto",
    contact: "9732532850",
    address:
      "4B, Baishnabghata Rd, near Padmasree Hall, Garia, Kolkata, 700047",
    url: "https://www.pixipfoto.in/",
    rating: "5",
  },
  {
    name: "PIP Broadcast -Wedding Photography",
    contact: "9088276753",
    address: "60/44, Haripada Dutta Ln,Tollygunge, Kolkata, 700 033",
    url: "https://www.pipbroadcast.com/",
    rating: "5",
  },
  {
    name: "DM Digitals",
    contact: "97322 71700",
    address: "Ground Floor, v53/6, Vivekananda Sarani,Garia, Kolkata, 700084",
    url: "https://dmdigitals.com/",
    rating: "5",
  },
  {
    name: "Raja Das Photography",
    contact: "9831433888",
    address:
      "block 2, CIT Building, 23, Christopher Rd, Entally, Kolkata, 700014",
    url: "https://rajadasphotography.com/",
    rating: "5",
  },
  {
    name: "Akash HD Photography",
    contact: "9163725845",
    address: "47/1/H/16, Sir Syed Ahmed Rd, Entally, Kolkata, 700014",
    url: "https://akashhdphotography.in/",
    rating: "5",
  },
  {
    name: "Chandrasekhar Chakraborty Photography",
    contact: "9331007958",
    address: "62/3, Bondel Rd,  Ballygunge, Kolkata, 700019",
    url: "https://www.chandrasekharchakraborty.com/",
    rating: "5",
  },
  {
    name: "Wedding Creation",
    contact: "9903439002",
    address: "30/3, Rajdanga Main Road Narkelbagan Kolkata,700107",
    url: "https://weddingcreation.net/",
    rating: "5",
  },
  {
    name: "MOL - Moments of life ",
    contact: "7003362340",
    address: "95, Ruby Park South, Kasba, Kolkata 700078",
    url: "",
    rating: "4",
  },
  {
    name: "Kolkata Wedding Photographers ",
    contact: "6289073211",
    address: "8H, Roy Para Bye Ln, Sinthee, Kolkata, 700050",
    url: "",
    rating: "4",
  },
  {
    name: "Colour Copy",
    contact: "8697742832",
    address: "DD 66/A, Narayantola East, Ashwini Nagar, Kolkata, 700159",
    url: "",
    rating: "4",
  },
  {
    name: "Abhishek Roy Photography",
    contact: "9531590365",
    address: "Survey Park, Santoshpur, Kolkata, 700075",
    url: "",
    rating: "4",
  },
  {
    name: "Wedding  Folks",
    contact: "7003246959",
    address: "A/30, Ramkrishna Upanibesh, Jadavpur, Kolkata, 700092",
    url: "",
    rating: "4",
  },
  {
    name: "Hashtag Chobi",
    contact: "7003216321",
    address:
      "103/ 1A, Raja Dinendra St, Manicktala, Gouri Bari,  Kolkata, 700006",
    url: "",
    rating: "4",
  },
  {
    name: "Naicy Photography and Digital",
    contact: "9830296612",
    address:
      "2nd Floor, Saraswati Apartment, Dakshindari, South Dumdum, Kolkata 700048",
    url: "",
    rating: "4",
  },
  {
    name: "Rabin's Photography­",
    contact: "9038858523",
    address:
      "17/40A, Dakshindari Rd, Dakshindari, Kolkata, South Dumdum,700048",
    url: "https://rabinsphotography.com/",
    rating: "5",
  },
  {
    name: "Sen Photography",
    contact: "9903113011",
    address:
      "19 A, Satish Mukherjee Rd, near Jatin Das Metro Station, Kalighat, Kolkata,700026",
    url: "",
    rating: "5",
  },
  {
    name: "Lens Shadow Studio",
    contact: "8335005964",
    address:
      "57/1B, Harish Mukherjee Rd, Patuapara, Bhowanipore, Kolkata 700025",
    url: "https://lensshadow.com/",
    rating: "5",
  },
  {
    name: "Sombit Dey Photography",
    contact: "9830570102",
    address: "86, Abhedananda Rd, Garanhatta, Beniatola, Kolkata, W700006",
    url: "https://sombitdeyphotography.com/",
    rating: "5",
  },
  {
    name: "The Orchid Photography",
    contact: "9804565181",
    address:
      "57/A/3, kasthodanga link road, Shibrampur, Sarsuna, Kolkata,700061",
    url: "https://theorchidphotography.com/",
    rating: "5",
  },
  {
    name: "Piixonova",
    contact: "8013014015",
    address: "BF 70, BF Block, Sector 1, Bidhannagar, Kolkata, 700064",
    url: "https://piixonova.com/",
    rating: "5",
  },
  {
    name: "The Weddart",
    contact: "7003540078",
    address:
      "Baghajatin Colony, NO 2 Chittaranjan Colony, A/8, Baghajatin Colony, Kolkata, 700092",
    url: "https://theweddart.com/",
    rating: "5",
  },
  {
    name: "Pixtory Weddings",
    contact: "9851421015",
    address:
      "Ground Floor, Sonali Apartment, Sukanta Pallly Rd, Tarulia, Krishnapur, Rajarhat, Kolkata, 700102",
    url: "",
    rating: "5",
  },
  {
    name: "FliqaIndia",
    contact: "9641817485",
    address:
      "7th Floor, Monibhandar Building, Webel Bhavan Premises, GP Block, Sector V, Bidhannagar, Kolkata,700091",
    url: "https://www.fliqaindia.com/",
    rating: "5",
  },
  {
    name: "QpidIndia",
    contact: "8910014860",
    address: "117, Jugipara Rd, Satgachi, Dum Dum, Kolkata, West Bengal 700028",
    url: "https://qpidindia.in/",
    rating: "5",
  },
  {
    name: "Jeet Biswas Photography",
    contact: "9903026622",
    address:
      "Apartment, 2Nd Floor, 16, Russa Rd South 2nd Ln, near M R Bangur Hospital,  Tollygunge, Kolkata, 700033",
    url: "https://jeetphotography.in/",
    rating: "5",
  },
  {
    name: "Muddyearth",
    contact: "9681798664",
    address:
      "1st floor, B, 41, Ramkrishna Upanibesh, Jadavpur, Kolkata, 700092",
    url: "http://www.muddyearth.com/",
    rating: "5",
  },
  {
    name: "Suswagatam Photos",
    contact: "9593565359",
    address: "Eastend Park, Kalikapur, Haltu, Kolkata, 700099",
    url: "",
    rating: "5",
  },
  {
    name: "Ritabrata Mukherjee Photography",
    contact: "9163060911",
    address: "9, 13, Hem Chandra Mukherjee Rd, Purba Barisha, Kolkata, 700008",
    url: "https://www.ritabrata.com/",
    rating: "4",
  },
  {
    name: "Swiping Stories Photography",
    contact: "9433528704",
    address: "30/49 Nayapatty Road,South Dum Dum, Kolkata 700055,",
    url: "http://www.swipingstory.com/",
    rating: "4",
  },
  {
    name: "Creative digital Eye",
    contact: "9804292515",
    address:
      "60a, Keshab Chandra Sen St, City College, Baithakkhana, Kolkata,  700009",
    url: "https://creativedigitaleye.com/",
    rating: "4",
  },
  {
    name: "Ranjan Bhattacharya Photography",
    contact: "9830019666",
    address: "49/A, Vivekananda Sarani Rd, Kalikapur, Garfa, Kolkata, 700078",
    url: "http://www.ranjanb.in/",
    rating: "4",
  },
  {
    name: "Studio Chitrarupa",
    contact: "9674866347",
    address: "738 , Behala Chowrasta, Diamond Harbour Rd, Barisha, Kolkata, ",
    url: "https://www.studiochitrarupa.net/",
    rating: "4",
  },
  {
    name: "MGD Photos",
    contact: "7603076013",
    address: "Sonamukhi Main Rd, Sonamukhi Daspara, Sarsuna, Kolkata, 700061",
    url: "",
    rating: "4",
  },
  {
    name: "Gupta Photography",
    contact: "9831218141",
    address: "Kalibazar Rd, Green Park, Laskar Pur, Kolkata, 700153",
    url: "",
    rating: "4",
  },
  {
    name: "Studio Pomegranate",
    contact: "8420199548",
    address:
      "2nd Floor, 4C, Wood St, next to Lifeline Nursing Home, Kankaria Estates, Elgin, Kolkata,700016",
    url: "https://www.studiopomegranate.in/",
    rating: "4",
  },
  {
    name: "Passionate Photography",
    contact: "9830725195",
    address: "Dumdum, 1/15, Gorakshabasi Rd,  Nagerbazar, Kolkata, 700028",
    url: "",
    rating: "4",
  },
  {
    name: "The Waves of Love",
    contact: "8981042106",
    address: "BLOCK-1, 11/26, Beleghata, Kolkata, 700010",
    url: "",
    rating: "4",
  },
  {
    name: "Charcoal & Vermillion",
    contact: "9163515627",
    address: "25A, 2nd Rd, Eastend Park, Kalikapur, Haltu, Kolkata, 700099",
    url: "https://charcoalandvermillion.com",
    rating: "4",
  },
];

export const artistsData = [
  {
    name: "The Gargi Chakraborty Studio ",
    contact: "7044244826",
    address:
      "Merlin Isand 209, Picnic Garden Rd, Kata Pukur, Kustia, Kolkata,700039",
    url: "https://thegargichakraborty.com/",
    rating: "5",
  },
  {
    name: "Debi's Premier Makeup Artist",
    contact: "8017874075",
    address: "42, 17, Murari Pukur Rd, Bagmari, Kolkata 700067",
    url: "https://debispremiermakeup.business.site/",
    rating: "5",
  },
  {
    name: "Priyanka's Beauty Box",
    contact: "7980204962",
    address: "HA323.1st Floor, Salt lake. Sector - 3. , Kolkata 700106.",
    url: "https://priyankasbeautybox.com/",
    rating: "5",
  },
  {
    name: "The Glamorous Makeover",
    contact: "9836220214",
    address: "1st Floor, 306, Ajoy Nagar, Santoshpur, Kolkata 700075",
    url: "https://www.theglamorousmakeover.com/",
    rating: "5",
  },
  {
    name: "Anubrati's Makeup Studio",
    contact: "9903091418",
    address:
      "174, Rajdanga Sarat Park Rd, Sector A, East Kolkata Twp, Kolkata 700107",
    url: "https://anubratismakeupstudio.com/",
    rating: "5",
  },
  {
    name: "Riya Ghosh Makeup Artist",
    contact: "9547306031",
    address:
      "Dumdum, Ghosh-para, 4 no gatenear Dumdum metro station ,Dumdum ,Kolkata,  700074",
    url: "https://makeup-artist-riya-ghosh-academy-riyas-pro-makeup.business.site/",
    rating: "5",
  },
  {
    name: "Arjun Das Make-up Artist",
    contact: "9674274251",
    address:
      "26A, Kshetra Mohan Naskar Rd, Vivekananda Nagar, Regent Park, Kolkata,700040",
    url: "https://www.arjundasmakeupartist.com/",
    rating: "4",
  },
  {
    name: "Moumita Makeup",
    contact: "8697750011",
    address: "Indu Apt, 98, Garia Main Rd, Mahamaya Tala, Kolkata 700084",
    url: "https://moumitamakeup.com/",
    rating: "5",
  },
  {
    name: "Sonu's Makeup Studio",
    contact: "8240806496",
    address: "331, Preyasi Apartment ,Garia Station Rd, Kolkata 700084",
    url: "http://sonusmakeupstudio.co.in/",
    rating: "5",
  },
  {
    name: "Sana Sarwar Make Up Studio",
    contact: "9007641337",
    address:
      "7A, Congress Exhibition Road ,Park Circus, Ballygunge, Kolkata 700017",
    url: "https://sanasarwar.com/",
    rating: "5",
  },
  {
    name: "Mousumi's Makeover",
    contact: "9830811281",
    address: "2, Gopi Bose Ln, Bowbazar, Kolkata, West Bengal 700012",
    url: "",
    rating: "5",
  },
  {
    name: "Priyanka's Beauty Box",
    contact: "7980204962",
    address: "HA Block, Salt Lake, Sector 3, Kolkata, 700106",
    url: "",
    rating: "5",
  },
  {
    name: "Riya Ghosh Makeup",
    contact: "9547306031",
    address: "Ghosh-para, 4 no gate, Dum Dum, Kolkata, 700074",
    url: "",
    rating: "5",
  },
  {
    name: "Jas Makeover ",
    contact: "8296636475",
    address: "133, chaltabagan, Vivekananda Rd, Manicktala, Kolkata, 700006",
    url: "",
    rating: "5",
  },
  {
    name: "Swapna's Makeover",
    contact: "9007564060",
    address: "4, PO :21, Chittaranjan Colony, Jadavpur, Kolkata, 700032",
    url: "",
    rating: "5",
  },
  {
    name: "Rimi Makeover",
    contact: "8240053376",
    address:
      "130, Rajshekhar Bose Sarani, Bakul Bagan, Bhowanipore, Kolkata 700025",
    url: "https://rimimakeoverkolkata.in/",
    rating: "4",
  },
  {
    name: "Piyali'z Makeup & Beauty",
    contact: "8013698181",
    address:
      "274/24 Nababithi, Mahatma Gandhi Rd, opp. SBI kabardanga, Kolkata,700104",
    url: "https://www.piyalizacademy.in/",
    rating: "4",
  },
  {
    name: "Leesa's Makeover",
    contact: "8369471636",
    address: "Kankurgachi CIT Building Block 4 Flat 22, Kolkata,700054",
    url: "",
    rating: "4",
  },
  {
    name: "Titli Beauty & Makeup",
    contact: "9051288331",
    address: "V1, Gosto tala, 4/2, Vivekananda Park, Kamdahari, Kolkata,700084",
    url: "https://www.titliweddingmakeup.com/",
    rating: "4",
  },
  {
    name: "Ruma's Makeup Studio",
    contact: "9038104865",
    address: "78C, Aswini Nagar, Tollygunge, Kolkata,700040",
    url: "",
    rating: "4",
  },
  {
    name: "Shruti Jain Makeup ",
    contact: "8229973611",
    address: "Kolkata",
    url: "https://www.instagram.com/alilextra_byshruti/",
    rating: "4",
  },
  {
    name: "Reshmi Makeup",
    contact: "9836672590",
    address:
      "22/264, opposite of South City Mall, Jodhpur Park, Kolkata,700045",
    url: "",
    rating: "4",
  },
  {
    name: "The Makeup Saga",
    contact: "7044002576",
    address: "3B, Dhakuria Station Rd, Dhakuria, Kolkata,700031",
    url: "",
    rating: "4",
  },
  {
    name: "Preetz Glam Makeup",
    contact: "9748870402",
    address:
      " 89 Somnath Lahiri Road, Chanditala Ln, New Alipore, Kolkata 700053",
    url: "",
    rating: "4",
  },
  {
    name: "Sayoni's Makeover Artistry",
    contact: "7003571668",
    address: "10, New, Parnasree Pally Rd, Parnasree Palli, Kolkata,700060",
    url: "https://sayonismakeover.com/",
    rating: "4",
  },
  {
    name: "Wake Up & Make Up",
    contact: "7003187626",
    address:
      "31, Mahendra Srimani Street, Sukea St, Manicktala, Kolkata, 700009",
    url: "http://www.wakeupandmakeup.in/",
    rating: "5",
  },
  {
    name: "Debasree Makeup",
    contact: "9804359552",
    address:
      " 85, Bishalakshmitala Rd, Parnasree Palli, Behala, Kolkata 700060",
    url: "",
    rating: "5",
  },
  {
    name: "Trina's Makeover",
    contact: "8420884659",
    address: "10/1, Kazi Para Rd, Parnasree Palli, Behala, Kolkata, 700060",
    url: "",
    rating: "5",
  },
  {
    name: "Pallavi Sinha Makeup",
    contact: "7001142119",
    address: "61, Shyama Prasad Mukherjee Rd, Hazra, Kalighat, Kolkata 700026",
    url: "",
    rating: "5",
  },
  {
    name: "Siddhart Makeover",
    contact: "9674910518",
    address: "73, Sisir bhadhury Sarani, opposite Duff Church, Kolkata, 700006",
    url: "",
    rating: "5",
  },
  {
    name: "Babliya Makeover",
    contact: "9073739851",
    address:
      "154/2/20A,Netaji Subhas Chandra Bose Road ,Tollygunge, Kolkata, 700040",
    url: "",
    rating: "5",
  },
];
