import type { Metadata } from 'next'
import CommunityForm from './CommunityForm'
import PageTitle from '@/components/sheared/PageTitle'
import Community from './Community'

export const metadata: Metadata = {
    title: 'Blogs - Dremable',
    description: 'Generated by create next app',
}

const blog: React.FC = () => {
    return (
        <div className='flex flex-col items-center'>
            <PageTitle title='Our Community' />
            <CommunityForm />
            <Community />
        </div>
    );
};

export default blog